name: dka-go-microservices

services:

  mongo:
    image: mongo:latest
    container_name: dka-go-microservices-mongo
    hostname: dka-go-microservices-mongo
    deploy:
      resources:
        reservations:
          memory: 200M
          cpus: '0.7'
        limits:
          memory: 500M
          cpus: '1.0'
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Cyberhack2010
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    ports:
      - target: 27017
        published: 27017
        host_ip: 0.0.0.0
        protocol: tcp

volumes:
  mongo-data:
    driver: local